version: 2

project_name: gostore

before:
  hooks:
    - mise r build
    - mise r test
    - rm -rf dist

builds:
  - id: gostore
    main: ./cmd/gostore
    binary: gostore
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/UsingCoding/gostore/internal/cli/cmd/app.Version={{.RawVersion}}
      - -X github.com/UsingCoding/gostore/internal/cli/cmd/app.Commit={{.Commit}}

brews:
  - name: gostore
    description: "Secret store manager"
    homepage: "https://github.com/UsingCoding/gostore"
    repository:
      owner: UsingCoding
      name: homebrew-public

archives:
  - format: tar.gz
    # Use zip for Windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^version-increment:"

release:
  github:
    owner: UsingCoding
    name: gostore
